name: speech
description: Text-to-Speech and Speech-to-Text services for Metalore.
version: 0.5.1
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  flutter_tts: ^4.2.3

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0
