name: core
description: Core shared logic for Metalore
version: 0.5.1
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  meta: ^1.17.0
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
